#!/usr/bin/env python3
"""bench_e2e_collect.py — Parse QEMU UART log + stub_brain log; emit bench JSON.

Called by scripts/bench_e2e.sh after each QEMU run.  Also usable standalone:

    python3 tools/bench_e2e_collect.py \\
        --qemu-log   build/bench_logs/run0/qemu.log \\
        --stub-log   build/bench_logs/run0/stub.log \\
        --kernel-elf target/riscv64imac-unknown-none-elf/release/kernel \\
        --sha        abc123def456 \\
        --out        bench/results/abc123def456.json

Metrics extracted
-----------------
boot_ms          Time from QEMU launch (recorded externally as QEMU_LAUNCH_TS
                 written to the log header) to first "[NET] Stack ready" line
                 (or first STATUS packet line in stub log, whichever comes first).

wcet_us          Parsed from "[WCET]  <name> <min> <max> <avg> <count> <viol>"
                 lines printed by wcet_report() when the harness sends "wcet"
                 to the kernel shell via stdin.

jitter_ns        Parsed from "[JITTER]  <series> <min_ns> <max_ns> <samples>"
                 lines printed by jitter_report() via "wcet jitter".

rtt_ms           Computed from timestamp pairs logged by stub_brain when running
                 in --bench-rtt mode.  Under QEMU TCG the sensor pump is often
                 stalled so these are typically null.

throughput       Parsed from stub_brain summary lines
                 "rx[...] tx[ACTUATOR=N] duration=Ns".

footprint        Output of riscv64-unknown-elf-size on the kernel ELF.

All values are medians across the N_RUNS individual run results passed in.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import re
import statistics
import subprocess
import sys
import time
from typing import Any, Optional

# ── Schema version (bump when the top-level key set changes) ─────────────────
HARNESS_VERSION = "1.0"

# ── Regex patterns for kernel UART log ───────────────────────────────────────

# Marker that tells us the kernel network stack is up (reliable boot signal).
_RE_NET_READY = re.compile(r"\[NET\]\s+Stack ready")

# Shell banner — kernel entered interactive mode.
_RE_SHELL_READY = re.compile(r"Robot OS shell\s*[—-]")

# WCET report line:
# [WCET]  pid_loop               0          0          0       0      0
_RE_WCET_LINE = re.compile(r"\[WCET\]\s+(\w+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)")

# WCET report separator (skip these lines).
_RE_WCET_SEP = re.compile(r"\[WCET\]\s+[─\-─]+")

# ISR inline WCET probe (generated by the `probe!` macro in main.rs when
# a subcomponent inside the timer ISR takes > 1ms under QEMU TCG).
# Format: [ISR-WCET] <label> took <N> µs
# Used as a fallback to populate timer_isr.max when the shell `wcet`
# command cannot be injected (UART IRQ on different hart under SMP TCG).
_RE_ISR_WCET_LINE = re.compile(r"\[ISR-WCET\]\s+(\S+)\s+took\s+(\d+)\s+[µu]s")

# Jitter report line:
# [JITTER]  timer_isr       100000       120000        150
_RE_JITTER_LINE = re.compile(r"\[JITTER\]\s+(\w+)\s+(\d+)\s+(\d+)\s+(\d+)")

# Synthetic per-subsystem microbench line, emitted by `robot_os_bench`:
# [BENCH-RES] ipc.channel_send_recv iters=100 min_cycles=2730 max_cycles=2730
#             avg_cycles=2730 total_cycles=273000
# Header / separator lines (── run_all start/done ──) also start with
# [BENCH-RES] but their second token isn't dot-namespaced, so the regex
# requires `<subsystem>.<name>` to match.
_RE_BENCH_RES = re.compile(
    r"\[BENCH-RES\]\s+(\w+\.\w+)\s+iters=(\d+)\s+min_cycles=(\d+)\s+"
    r"max_cycles=(\d+)\s+avg_cycles=(\d+)\s+total_cycles=(\d+)"
)

# Harness-injected launch timestamp line:
# [BENCH-LAUNCH] 1748432400.123456
_RE_BENCH_LAUNCH = re.compile(r"\[BENCH-LAUNCH\]\s+([\d.]+)")

# Harness-injected NET-READY wallclock line:
# [BENCH-NETREADY] 1748432403.456
_RE_BENCH_NETREADY = re.compile(r"\[BENCH-NETREADY\]\s+([\d.]+)")

# ── Regex patterns for stub_brain log ────────────────────────────────────────

# First packet timestamp line (added by bench_brain wrapper):
# [BENCH-FIRST-PKT] 1748432403.567
_RE_BENCH_FIRST_PKT = re.compile(r"\[BENCH-FIRST-PKT\]\s+([\d.]+)")

# Stub summary: rx[SENSOR=12, STATUS=1] tx[ACTUATOR=4] duration=30s
_RE_STUB_SUMMARY = re.compile(r"rx\[([^\]]*)\]\s+tx\[ACTUATOR=(\d+)\]\s+duration=(\d+)s")

# Stub RTT lines (emitted by --bench-rtt mode):
# [BENCH-RTT] 12.34
_RE_BENCH_RTT = re.compile(r"\[BENCH-RTT\]\s+([\d.]+)")

# Sensor count in rx summary.
# bench_stub.py emits "rx[pkt=N]" (total received); original stub_brain.py
# emits "rx[SENSOR=N, STATUS=1]" or "rx[SENSOR_COMPACT=N]".
# This regex handles both forms.
_RE_RX_SENSOR = re.compile(r"(?:SENSOR|SENSOR_COMPACT|pkt)=(\d+)")

# ── Helpers ───────────────────────────────────────────────────────────────────


def _read(path: str) -> str:
    """Read a file; return empty string on error."""
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            return fh.read()
    except OSError:
        return ""


def _median_or_none(values: list[Optional[float]]) -> Optional[float]:
    """Median of non-None values; None if list is empty or all-None."""
    valid = [v for v in values if v is not None]
    if not valid:
        return None
    return statistics.median(valid)


def _percentile(sorted_data: list[float], pct: float) -> float:
    """Linear-interpolation percentile on a sorted list."""
    if not sorted_data:
        return 0.0
    idx = pct / 100.0 * (len(sorted_data) - 1)
    lo = int(idx)
    hi = min(lo + 1, len(sorted_data) - 1)
    frac = idx - lo
    return sorted_data[lo] * (1.0 - frac) + sorted_data[hi] * frac


# ── Per-run parsers ───────────────────────────────────────────────────────────


def parse_boot_ms(
    qemu_text: str,
    stub_text: str,
) -> Optional[float]:
    """
    Return boot time in ms.

    Strategy (in priority order):
    1. If qemu_text contains a [BENCH-LAUNCH] and [BENCH-NETREADY] line,
       return the delta.
    2. If stub_text contains a [BENCH-FIRST-PKT] and qemu_text contains
       a [BENCH-LAUNCH], return (first_pkt - launch) * 1000.
    3. Otherwise None.
    """
    m_launch = _RE_BENCH_LAUNCH.search(qemu_text)
    if not m_launch:
        return None
    launch_ts = float(m_launch.group(1))

    # Try [BENCH-NETREADY] first (more reliable than waiting for status pkt).
    m_ready = _RE_BENCH_NETREADY.search(qemu_text)
    if m_ready:
        return (float(m_ready.group(1)) - launch_ts) * 1000.0

    # Fall back to first TCP packet from stub.
    m_pkt = _RE_BENCH_FIRST_PKT.search(stub_text)
    if m_pkt:
        return (float(m_pkt.group(1)) - launch_ts) * 1000.0

    return None


def parse_wcet(qemu_text: str) -> dict[str, Optional[dict[str, Any]]]:
    """
    Parse [WCET] report lines.

    Returns a dict keyed by point name with sub-keys
    {min, max, avg, p99, violations} all in µs.
    p99 is not available from the kernel's report (it tracks only min/max/avg);
    we set it to max as a conservative upper bound.

    Fallback: if no [WCET] report lines are found (shell command injection failed
    due to UART IRQ hart-routing under QEMU SMP TCG), parse [ISR-WCET] inline
    probe lines and populate timer_isr.{min,max,avg} from them.
    """
    result: dict[str, Optional[dict[str, Any]]] = {}
    for m in _RE_WCET_LINE.finditer(qemu_text):
        name = m.group(1)
        min_us = int(m.group(2))
        max_us = int(m.group(3))
        avg_us = int(m.group(4))
        count = int(m.group(5))
        viol = int(m.group(6))
        if count == 0:
            continue  # skip zero-sample points
        result[name] = {
            "min": min_us,
            "max": max_us,
            "avg": avg_us,
            "p99": max_us,  # kernel doesn't emit p99; use max
            "violations": viol,
        }

    # Fallback: parse [ISR-WCET] inline probes.
    # Under QEMU TCG SMP, these are the only WCET numbers we reliably get
    # because UART IRQ-driven shell input doesn't work on all harts.
    isr_wcet_samples: dict[str, list[int]] = {}
    for m in _RE_ISR_WCET_LINE.finditer(qemu_text):
        label = m.group(1)
        val_us = int(m.group(2))
        isr_wcet_samples.setdefault(label, []).append(val_us)

    if isr_wcet_samples and "timer_isr" not in result:
        # Aggregate all [ISR-WCET] samples into a synthetic timer_isr entry.
        all_vals: list[int] = []
        for vals in isr_wcet_samples.values():
            all_vals.extend(vals)
        if all_vals:
            result["timer_isr"] = {
                "min": min(all_vals),
                "max": max(all_vals),
                "avg": int(sum(all_vals) / len(all_vals)),
                "p99": max(all_vals),  # conservative
                "violations": 0,  # inline probes don't track violations
            }

    return result


def parse_bench_synth(qemu_text: str) -> dict[str, dict[str, int]]:
    """
    Parse [BENCH-RES] synthetic microbench lines.

    Returns a flat dict keyed by `<subsystem>.<bench_name>` (e.g.
    "ipc.channel_send_recv"), each value a dict
    {iters, min_cycles, max_cycles, avg_cycles, total_cycles}.

    Placeholder entries (iters=0) and run_all banner lines are skipped.
    If a name appears multiple times in the log (auto-report ran more
    than once, or the harness re-emitted), the LAST occurrence wins —
    matches the "freshest sample" rule used by `parse_wcet`.
    """
    result: dict[str, dict[str, int]] = {}
    for m in _RE_BENCH_RES.finditer(qemu_text):
        name = m.group(1)
        iters = int(m.group(2))
        if iters == 0:
            continue  # placeholder / disabled subsystem
        result[name] = {
            "iters": iters,
            "min_cycles": int(m.group(3)),
            "max_cycles": int(m.group(4)),
            "avg_cycles": int(m.group(5)),
            "total_cycles": int(m.group(6)),
        }
    return result


def parse_jitter(qemu_text: str) -> dict[str, Optional[dict[str, Any]]]:
    """
    Parse [JITTER] report lines.

    Returns a dict keyed by series name with sub-keys {min, max}.
    Units: nanoseconds (as reported by kernel).
    """
    result: dict[str, Optional[dict[str, Any]]] = {}
    for m in _RE_JITTER_LINE.finditer(qemu_text):
        name = m.group(1)
        min_ns = int(m.group(2))
        max_ns = int(m.group(3))
        samples = int(m.group(4))
        if "unused" in name or samples == 0:
            continue
        result[name] = {"min": min_ns, "max": max_ns}
    return result


def parse_rtt(stub_text: str) -> dict[str, Optional[float]]:
    """
    Parse [BENCH-RTT] lines from bench stub log.

    Returns p50/p95/p99/stddev/n_samples (all in ms), or all None.
    """
    samples = [float(m.group(1)) for m in _RE_BENCH_RTT.finditer(stub_text)]
    if not samples:
        return {"p50": None, "p95": None, "p99": None, "stddev": None, "n_samples": 0}
    s = sorted(samples)
    n = len(s)
    return {
        "p50": round(_percentile(s, 50.0), 3),
        "p95": round(_percentile(s, 95.0), 3),
        "p99": round(_percentile(s, 99.0), 3),
        "stddev": round(statistics.stdev(s) if n > 1 else 0.0, 3),
        "n_samples": n,
    }


def parse_throughput(stub_text: str) -> dict[str, Optional[float]]:
    """
    Parse stub summary line to derive msgs/s for each scenario.

    Returns steady_msgs_per_s and burst_peak_msgs_per_s.
    burst_peak is null unless the stub was in burst mode.
    """
    # burst_peak is always extracted independently so it isn't lost even when
    # the summary line is missing (e.g. the steady-run stub timed out but the
    # burst line was appended from the burst scenario).
    burst_m = re.search(r"\[BENCH-BURST-PEAK\]\s+([\d.]+)", stub_text)
    burst_peak: Optional[float] = float(burst_m.group(1)) if burst_m else None

    m = _RE_STUB_SUMMARY.search(stub_text)
    if not m:
        return {"steady_msgs_per_s": None, "burst_peak_msgs_per_s": burst_peak}
    rx_part = m.group(1)
    tx_count = int(m.group(2))
    duration = int(m.group(3))

    # Count received sensor packets.
    rx_total = sum(int(mm.group(1)) for mm in _RE_RX_SENSOR.finditer(rx_part))
    total_msgs = rx_total + tx_count
    if duration <= 0:
        return {"steady_msgs_per_s": None, "burst_peak_msgs_per_s": burst_peak}

    steady = round(total_msgs / duration, 2)

    return {"steady_msgs_per_s": steady, "burst_peak_msgs_per_s": burst_peak}


def parse_footprint(kernel_elf: str) -> dict[str, Optional[int]]:
    """
    Run riscv64-unknown-elf-size -A on the kernel ELF and extract section sizes.
    """
    size_tool = None
    for candidate in [
        "riscv64-unknown-elf-size",
        "/opt/homebrew/bin/riscv64-unknown-elf-size",
        "llvm-size",
        "size",
    ]:
        try:
            subprocess.run([candidate, "--version"], capture_output=True, check=False)
            size_tool = candidate
            break
        except FileNotFoundError:
            continue

    if size_tool is None or not os.path.exists(kernel_elf):
        return {
            "text_bytes": None,
            "rodata_bytes": None,
            "data_bytes": None,
            "bss_bytes": None,
            "total_bytes": None,
        }

    result = subprocess.run(
        [size_tool, "-A", kernel_elf], capture_output=True, text=True, check=False
    )
    text_sum = 0
    rodata_sum = 0
    data_sum = 0
    bss_sum = 0

    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) < 2:
            continue
        try:
            size = int(parts[1])
        except (ValueError, IndexError):
            continue
        sec = parts[0]
        if sec in (".text", ".text.boot"):
            text_sum += size
        elif sec in (".rodata", ".rodata.str1.8", ".rodata.str1.1"):
            rodata_sum += size
        elif sec == ".data":
            data_sum += size
        elif sec == ".bss":
            bss_sum += size

    total = text_sum + rodata_sum + data_sum + bss_sum
    return {
        "text_bytes": text_sum or None,
        "rodata_bytes": rodata_sum or None,
        "data_bytes": data_sum or None,
        "bss_bytes": bss_sum or None,
        "total_bytes": total or None,
    }


# ── Multi-run aggregators ─────────────────────────────────────────────────────


# RFC-0027 — split WCET output into (a) the kernel's fixed point set
# (carrying over as `wcet_us`) and (b) macro-generated per-function points
# (`wcet_per_fn.*`).  The kernel's `crates/drivers/wcet_points.json` is the
# source of truth.  If the index isn't reachable from the harness CWD we fall
# back to the historical hardcoded fixed set so the schema doesn't break.
_FIXED_WCET_FALLBACK = frozenset(
    {
        "pid_loop",
        "sensor_read",
        "ctx_switch",
        "timer_isr",
        "actuator_write",
        "net_send",
        "cnn_infer",
        "lidar_scan",
        "path_plan",
    }
)


def _load_fixed_wcet_names() -> frozenset[str]:
    """Read fixed-point names from `crates/drivers/wcet_points.json` (RFC-0027).

    Search relative to the brain repo's parent (sibling robot-os layout) plus
    a couple of common locations.  Cached after first read.
    """
    candidates = [
        os.path.join(
            os.path.dirname(__file__),
            "..",
            "..",
            "robot-os",
            "crates",
            "drivers",
            "wcet_points.json",
        ),
        os.path.join(
            os.path.dirname(__file__), "..", "robot-os", "crates", "drivers", "wcet_points.json"
        ),
    ]
    for c in candidates:
        if os.path.exists(c):
            try:
                with open(c, "r", encoding="utf-8") as fh:
                    idx = json.load(fh)
                fixed = idx.get("fixed_points", [])
                if isinstance(fixed, list):
                    return frozenset(fixed)
            except (json.JSONDecodeError, OSError):
                pass
    return _FIXED_WCET_FALLBACK


def _split_wcet(
    wcet: dict[str, Optional[dict[str, Any]]],
) -> dict[str, dict[str, Optional[dict[str, Any]]]]:
    """Partition by name into `wcet_us` (fixed) and `wcet_per_fn` (annotated)."""
    fixed_names = _load_fixed_wcet_names()
    wcet_us: dict[str, Optional[dict[str, Any]]] = {}
    wcet_per_fn: dict[str, Optional[dict[str, Any]]] = {}
    for name, sample in wcet.items():
        if name in fixed_names:
            wcet_us[name] = sample
        else:
            wcet_per_fn[name] = sample
    return {"wcet_us": wcet_us, "wcet_per_fn": wcet_per_fn}


def _median_bench_synth(
    runs: list[dict[str, dict[str, int]]],
) -> dict[str, dict[str, Any]]:
    """
    Aggregate [BENCH-RES] microbench results across runs.

    For each (subsystem.bench) name, take the median across runs of
    each numeric field.  Missing entries (subsystem disabled in a
    run) are skipped, not zeroed.  Output structure parallels
    `_median_wcet`: flat dict keyed by name.
    """
    all_names: set[str] = set()
    for r in runs:
        all_names.update(r.keys())

    out: dict[str, dict[str, Any]] = {}
    for name in all_names:
        sub_list = [r[name] for r in runs if name in r]
        if not sub_list:
            continue
        out[name] = {
            "iters": _median_or_none([s["iters"] for s in sub_list]),
            "min_cycles": _median_or_none([s["min_cycles"] for s in sub_list]),
            "max_cycles": _median_or_none([s["max_cycles"] for s in sub_list]),
            "avg_cycles": _median_or_none([s["avg_cycles"] for s in sub_list]),
            "total_cycles": _median_or_none([s["total_cycles"] for s in sub_list]),
        }
    return out


def _median_wcet(
    runs: list[dict[str, Optional[dict[str, Any]]]],
) -> dict[str, Optional[dict[str, Any]]]:
    """
    Aggregate WCET across runs by taking median of each numeric sub-field.

    Missing points (no samples in a run) are treated as missing, not zero.
    """
    all_names: set[str] = set()
    for r in runs:
        all_names.update(r.keys())

    out: dict[str, Optional[dict[str, Any]]] = {}
    for name in all_names:
        sub_list = [r[name] for r in runs if r.get(name) is not None]
        if not sub_list:
            out[name] = None
            continue
        out[name] = {
            "min": _median_or_none([s["min"] for s in sub_list]),
            "max": _median_or_none([s["max"] for s in sub_list]),
            "avg": _median_or_none([s["avg"] for s in sub_list]),
            "p99": _median_or_none([s["p99"] for s in sub_list]),
            "violations": _median_or_none([s["violations"] for s in sub_list]),
        }
    return out


def _median_jitter(
    runs: list[dict[str, Optional[dict[str, Any]]]],
) -> dict[str, Optional[dict[str, Any]]]:
    all_names: set[str] = set()
    for r in runs:
        all_names.update(r.keys())

    out: dict[str, Optional[dict[str, Any]]] = {}
    for name in all_names:
        sub_list = [r[name] for r in runs if r.get(name) is not None]
        if not sub_list:
            out[name] = None
            continue
        out[name] = {
            "min": _median_or_none([s["min"] for s in sub_list]),
            "max": _median_or_none([s["max"] for s in sub_list]),
        }
    return out


def _median_rtt(runs: list[dict[str, Optional[float]]]) -> dict[str, Any]:
    all_samples = []
    for r in runs:
        n = r.get("n_samples") or 0
        all_samples.append(n)

    total_n = sum(all_samples)
    if total_n == 0:
        return {"p50": None, "p95": None, "p99": None, "stddev": None, "n_samples": 0}
    return {
        "p50": _median_or_none([r.get("p50") for r in runs]),
        "p95": _median_or_none([r.get("p95") for r in runs]),
        "p99": _median_or_none([r.get("p99") for r in runs]),
        "stddev": _median_or_none([r.get("stddev") for r in runs]),
        "n_samples": total_n,
    }


def _median_throughput(runs: list[dict[str, Optional[float]]]) -> dict[str, Optional[float]]:
    return {
        "steady_msgs_per_s": _median_or_none([r.get("steady_msgs_per_s") for r in runs]),
        "burst_peak_msgs_per_s": _median_or_none([r.get("burst_peak_msgs_per_s") for r in runs]),
    }


# ── Main entry ────────────────────────────────────────────────────────────────


def collect(
    run_dirs: list[str],
    kernel_elf: str,
    sha: str,
    out_path: str,
    qemu_version: str = "unknown",
    host: str = "darwin-arm64",
    qemu_smp: Optional[int] = None,
    qemu_icount_shift: Optional[int] = None,
    qemu_rtc_base: Optional[str] = None,
) -> dict[str, Any]:
    """
    Parse logs from each run directory, aggregate medians, write JSON.

    Each `run_dir` must contain:
      qemu.log  — QEMU UART output (with [BENCH-LAUNCH] header injected)
      stub.log  — stub_brain output (with optional [BENCH-RTT] lines)
    """
    boot_list: list[Optional[float]] = []
    wcet_list: list[dict[str, Any]] = []
    jitter_list: list[dict[str, Any]] = []
    rtt_list: list[dict[str, Any]] = []
    tput_list: list[dict[str, Any]] = []
    bench_synth_list: list[dict[str, dict[str, int]]] = []

    for d in run_dirs:
        qemu_text = _read(os.path.join(d, "qemu.log"))
        stub_text = _read(os.path.join(d, "stub.log"))

        boot_list.append(parse_boot_ms(qemu_text, stub_text))
        wcet_list.append(parse_wcet(qemu_text))
        jitter_list.append(parse_jitter(qemu_text))
        rtt_list.append(parse_rtt(stub_text))
        tput_list.append(parse_throughput(stub_text))
        bench_synth_list.append(parse_bench_synth(qemu_text))

    footprint = parse_footprint(kernel_elf)

    # QEMU reproducibility tags: each result is stamped with the harness
    # mode that produced it so a regression diff can tell "real change" from
    # "different bench mode".  qemu_icount_shift is None when icount is off.
    meta: dict[str, Any] = {
        "sha": sha,
        "config_sha": sha,  # same SHA; no separate .config here
        "defconfig": "qemu",
        "qemu_version": qemu_version,
        "host": host,
        "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "harness_version": HARNESS_VERSION,
        "n_runs": len(run_dirs),
    }
    if qemu_smp is not None:
        meta["qemu_smp"] = qemu_smp
    if qemu_icount_shift is not None:
        meta["qemu_icount_shift"] = qemu_icount_shift
    if qemu_rtc_base is not None:
        meta["qemu_rtc_base"] = qemu_rtc_base

    result: dict[str, Any] = {
        "meta": meta,
        "rtt_ms": _median_rtt(rtt_list),
        "throughput": _median_throughput(tput_list),
        "boot_ms": _median_or_none(boot_list),
        # Split WCET points: the 5 (now 9, after net_send / cnn_infer / lidar_scan
        # / path_plan slot expansion) FIXED kernel points live under wcet_us;
        # `#[wcet(N_us)]` macro-generated per-function points (RFC-0027) live
        # under wcet_per_fn parallel to it.  The split is driven by the kernel's
        # wcet_points.json index — which lists fixed_points by name, anything
        # not in that list is per-function.
        **_split_wcet(_median_wcet(wcet_list)),
        "jitter_ns": _median_jitter(jitter_list),
        # Synthetic per-subsystem microbenches (robot_os_bench, RFC-0027
        # extension).  Stable across runs because each bench is a tight
        # in-kernel loop bracketed by a single rdcycle pair.
        "bench_synth": _median_bench_synth(bench_synth_list),
        "footprint": footprint,
    }

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=2)
        fh.write("\n")

    return result


def _summary_line(data: dict[str, Any]) -> str:
    """Return the 1-line summary printed to stdout."""
    rtt_p99 = data["rtt_ms"].get("p99")
    boot = data.get("boot_ms")
    tput = data["throughput"].get("steady_msgs_per_s")
    fp = data["footprint"].get("total_bytes")

    rtt_str = f"{rtt_p99:.1f}ms" if rtt_p99 is not None else "null"
    boot_str = f"{boot:.0f}ms" if boot is not None else "null"
    tx_str = f"{tput:.1f}pkt/s" if tput is not None else "null"
    fp_str = f"{fp // 1024}KiB" if fp is not None else "null"

    return f"[BENCH] rtt_p99={rtt_str} boot={boot_str} tx={tx_str} footprint={fp_str}"


# ── CLI ───────────────────────────────────────────────────────────────────────


def _cli() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--run-dirs",
        nargs="+",
        required=True,
        help="one or more directories each containing qemu.log + stub.log",
    )
    ap.add_argument("--kernel-elf", required=True)
    ap.add_argument("--sha", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--qemu-version", default="unknown")
    ap.add_argument("--host", default="darwin-arm64")
    # Reproducibility tags.  Empty strings → field omitted from JSON meta.
    ap.add_argument(
        "--qemu-smp", default="", help="SMP count used (integer; empty = omit from meta)"
    )
    ap.add_argument(
        "--qemu-icount-shift",
        default="",
        help="icount shift value (integer; empty = icount off, omit from meta)",
    )
    ap.add_argument(
        "--qemu-rtc-base", default="", help="pinned RTC base date (e.g. 2020-01-01; empty = omit)"
    )
    args = ap.parse_args()

    def _opt_int(s: str) -> Optional[int]:
        return int(s) if s else None

    def _opt_str(s: str) -> Optional[str]:
        return s if s else None

    data = collect(
        run_dirs=args.run_dirs,
        kernel_elf=args.kernel_elf,
        sha=args.sha,
        out_path=args.out,
        qemu_version=args.qemu_version,
        host=args.host,
        qemu_smp=_opt_int(args.qemu_smp),
        qemu_icount_shift=_opt_int(args.qemu_icount_shift),
        qemu_rtc_base=_opt_str(args.qemu_rtc_base),
    )

    print(_summary_line(data))
    return 0


if __name__ == "__main__":
    sys.exit(_cli())
